name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-dependencies

      - name: Run tests
        run: pnpm test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-dependencies

      - name: Build Storybook
        run: pnpm run build-storybook

      - name: Upload Storybook build
        uses: actions/upload-artifact@v3
        with:
          name: storybook-build
          path: storybook-static

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Storybook build
        uses: actions/download-artifact@v3
        with:
          name: storybook-build
          path: storybook-static

      - name: Deploy Storybook
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static

      - name: Output Storybook URL
        uses: actions/github-script@v6
        with:
          script: |
            const url = process.env.STORYBOOK_URL;
            core.summary
              .addHeading('Storybook Deployment')
              .addLink('View deployed Storybook', url)
              .write();
