name: Deploy Storybook

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-dependencies

      - name: Run tests
        run: pnpm test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-dependencies

      - name: Build Storybook
        run: pnpm run build-storybook

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: storybook-static
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./storybook-static

      - name: Publish to GitHub Pages
        id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: ./storybook-static

      - name: Output URL
        if: success()
        run: echo "Deployed to ${{ steps.build-publish.outputs.url }}"
